#!/bin/sh
#
# ZWARE local (CE) init script
#
# Author: Angela
#
### BEGIN INIT INFO
# Provides:       zware-service
# Required-Start: $local_fs $network
# Required-Stop:  $local_fs $network
# Should-Start:   zipgateway
# Should-Stop:    zipgateway
# Default-Start:  2 3 4 5
# Default-Stop:   0 1 6
# Description:    zware-service
### END INIT INFO

SERVICE_NAME="zware-local"
BASE_PATH="/medha_gateway/local"
USER="debian"

INSTALL_PATH="$BASE_PATH/install"

start()
{
	echo "Starting $SERVICE_NAME"

	if [ -x ${BASE_PATH}/config/zipgateway/zipgateway-networkcheck.sh ]; then
		"${BASE_PATH}/config/zipgateway/zipgateway-networkcheck.sh"
	fi
	#su ${USER} "${BASE_PATH}/service/service.sh"  start
	"${BASE_PATH}/service/service.sh"  start
	sudo service zipgateway stop
	sudo service zipgateway start
	sudo service zwave_app stop
	sudo service zwave_app start
	printf "."

	sleep 1
}

stop()
{
	echo "Stopping $SERVICE_NAME"

	#su ${USER} "${BASE_PATH}/service/service.sh"  stop
	"${BASE_PATH}/service/service.sh"  stop

	printf "."

	sleep 1
}

restart()
{
	$0 stop
	$0 start
}

usage()
{
	echo "Usage: $0 {start|stop|restart|status}"
	exit 1
}

case "$1" in
	start)
		start
		;;
	stop)
		stop
		;;
	restart)
		restart
		;;
	*)
		usage
		;;
esac

exit 0
